---
- name: Install Terraform
  hosts: all
  become: yes

  tasks:
  - name: Update package list
    apt:
      update_cache: yes

  - name: Install unzip package
    apt:
      name: unzip
      state: present
       
  - name: Download Terraform package
    get_url:
      url: https://releases.hashicorp.com/terraform/1.4.0-alpha20221207/terraform_1.4.0-alpha20221207_linux_amd64.zip
      dest: /tmp/terraform.zip

  - name: Extract Terraform package
    unarchive:
      src: /tmp/terraform.zip
      dest: /usr/local/bin/
      remote_src: yes

  - name: Remove Terraform package
    file:
      path: /tmp/terraform.zip
      state: absent

  - name: Check Terraform version
    shell: terraform version